
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.DeleteJson;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORAZON = 8;
  public static final int COMA = 6;
  public static final int TREBOL = 9;
  public static final int DELETE_2 = 13;
  public static final int DELETE_1 = 12;
  public static final int ENTERO = 7;
  public static final int DIAMANTE = 10;
  public static final int EOF = 0;
  public static final int LLAVE_C = 3;
  public static final int LLAVE_A = 2;
  public static final int COMILLAS = 4;
  public static final int error = 1;
  public static final int DOS_PUNTOS = 5;
  public static final int PICA = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVE_A",
  "LLAVE_C",
  "COMILLAS",
  "DOS_PUNTOS",
  "COMA",
  "ENTERO",
  "CORAZON",
  "TREBOL",
  "DIAMANTE",
  "PICA",
  "DELETE_1",
  "DELETE_2"
  };
}

